# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KanbanMd < Formula
  desc "A file-based Kanban tool powered by Markdown"
  homepage "https://github.com/antopolskiy/kanban-md"
  version "0.13.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.13.5/kanban-md_0.13.5_darwin_amd64.tar.gz"
      sha256 "1231f97727f313b6c78a1653be360d22a8ed27dd2dedfafc9e4cdc30e65ab5fb"

      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.13.5/kanban-md_0.13.5_darwin_arm64.tar.gz"
      sha256 "73233d01d3f0d9650fa418ea78f785d9866b595d783e63dc92b98144b27e4181"

      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.13.5/kanban-md_0.13.5_linux_amd64.tar.gz"
      sha256 "358dc8665a741da9864514b713dfa56007d41ed27ad4a30272f0ea4f504887f9"
      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.13.5/kanban-md_0.13.5_linux_arm64.tar.gz"
      sha256 "90385531867df92afac56d508e1357f113e10c41c22e97f9877b8db030415fc8"
      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
  end
end
