# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KanbanMdTui < Formula
  desc "Interactive terminal UI for kanban-md boards"
  homepage "https://github.com/antopolskiy/kanban-md"
  version "0.28.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.28.0/kanban-md-tui_0.28.0_darwin_amd64.tar.gz"
      sha256 "d0170ec0274b066792bab8af0a174e47142bd08017f37ef82f3c47e64b4248d9"

      def install
        bin.install "kanban-md-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.28.0/kanban-md-tui_0.28.0_darwin_arm64.tar.gz"
      sha256 "ca1fe18bdc2ddeff9eb34ab4eb31c173411d53a19b577922e1e91b0cc876642d"

      def install
        bin.install "kanban-md-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.28.0/kanban-md-tui_0.28.0_linux_amd64.tar.gz"
      sha256 "cd28f72c4413924fe89760d26b7f776151870e02f0e9c476ca10e2a1b432332f"
      def install
        bin.install "kanban-md-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.28.0/kanban-md-tui_0.28.0_linux_arm64.tar.gz"
      sha256 "376c58e45476f419b42ba89b670e675c32442554c475eb738f9678c464c9e0d7"
      def install
        bin.install "kanban-md-tui"
      end
    end
  end
end
