# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KanbanMd < Formula
  desc "A file-based Kanban tool powered by Markdown"
  homepage "https://github.com/antopolskiy/kanban-md"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.17.0/kanban-md_0.17.0_darwin_amd64.tar.gz"
      sha256 "036e2eb29e71ae13d1d3535c3c1d99471cbfdb2b7f781daa257baed871f9d658"

      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.17.0/kanban-md_0.17.0_darwin_arm64.tar.gz"
      sha256 "f61bbb8bba5e8db6c160c04ceb28d29e9d23989be97b22702fca13a175ca682a"

      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.17.0/kanban-md_0.17.0_linux_amd64.tar.gz"
      sha256 "c5b5361ab1bcbfb3580752ab2c5e3f78ec478c5989be5373178654ff683d8218"
      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antopolskiy/kanban-md/releases/download/v0.17.0/kanban-md_0.17.0_linux_arm64.tar.gz"
      sha256 "525dbad097cff9759ccb29b3d5346b20539cf10db0b8a0ea5c1f977fdfe88c55"
      def install
        bin.install "kanban-md"
        bin.install_symlink bin/"kanban-md" => "kbmd"
        generate_completions_from_executable(bin/"kanban-md", "completion")
        generate_completions_from_executable(bin/"kbmd", "completion")
      end
    end
  end
end
